version: "3.8"
services:
  unifi-db:
    image : mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
#      - ./docker-unifi-network-application/db/data:/data/db
      - ./unifi/docker-unifi-network-application/db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro #absolute path required
    ports:
      - 27017:27017
    restart: unless-stopped
    
  unifi-network-application: 
    image: lscr.io/linuxserver/unifi-network-application:latest 
    container_name: unifi-network-application
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 
      - MEM_STARTUP=1024 
      - MONGO_TLS= 
    volumes: 
      - /docker-unifi-network-application/config:/config 
    ports: 
      - 8443:8443 
      - 3478:3478/udp 
      - 10001:10001/udp 
      - 8080:8080 
      - 1900:1900/udp 
      - 8843:8843 
      - 8880:8880 
      - 6789:6789 
      - 5514:5514/udp 
    restart: unless-stopped 
    depends_on:
      - unifi-db
